name: SimpleNPC
version: 1.3.1
main: me.szilprog.simplenpc.Main
api-version: 1.16
commands:
  reloadnpc:
    description: Reload the plugin
    usage: /reloadnpc
    permission: npc.reload
  npc:
    description: Create/delete NPCs
    usage: /npc create/delete
    permission: npc.admin

