name: SimpleNPC
version: 2.6.2
main: me.szilprog.simplenpc.Main
api-version: 1.16
commands:
  npc:
    description: Create/delete/edit/reload NPCs
    usage: /npc create/delete/edit/reload
    permission: npc.admin

