name: SimpleNPC
version: ${project.version}
main: me.szilprog.simplenpc.Main
api-version: 1.16
commands:
  reloadnpc:
    description: Reload the plugin
    usage: /npcreload
    permission: npc.reload
